-- CERVEJANDO COM DIEGO v20 — STRIPE + PEDIDOS + MAIORIDADE 18+
-- Execute este arquivo depois dos scripts anteriores do projeto.

alter table public.beers add column if not exists stock_quantity integer;

do $$ begin
  alter table public.beers add constraint beers_stock_quantity_nonnegative check (stock_quantity is null or stock_quantity >= 0) not valid;
exception when duplicate_object then null; end $$;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_code text not null unique,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  delivery_type text not null default 'pickup' check (delivery_type in ('pickup','delivery')),
  delivery_address jsonb,
  notes text,
  subtotal numeric(10,2) not null default 0,
  delivery_fee numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  status text not null default 'awaiting_payment' check (status in ('awaiting_payment','paid','preparing','ready','out_for_delivery','completed','cancelled')),
  payment_status text not null default 'pending' check (payment_status in ('pending','paid','failed','refunded')),
  payment_provider text,
  payment_reference text,
  stripe_checkout_session_id text,
  age_verified boolean not null default false,
  age_verified_at timestamptz,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.orders add column if not exists age_verified boolean not null default false;
alter table public.orders add column if not exists age_verified_at timestamptz;

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  beer_id uuid references public.beers(id) on delete set null,
  beer_slug text not null,
  beer_name_snapshot text not null,
  unit_price numeric(10,2) not null,
  quantity integer not null check (quantity > 0),
  line_total numeric(10,2) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  beer_id uuid references public.beers(id) on delete set null,
  order_id uuid references public.orders(id) on delete set null,
  movement_type text not null check (movement_type in ('sale','restock','adjustment','refund')),
  quantity integer not null,
  note text,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin(p_user_id uuid default auth.uid())
returns boolean language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.admin_users au where au.user_id = p_user_id);
$$;
revoke all on function public.is_admin(uuid) from public;
grant execute on function public.is_admin(uuid) to authenticated;

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.stock_movements enable row level security;
drop policy if exists "Admins read orders" on public.orders;
create policy "Admins read orders" on public.orders for select to authenticated using (public.is_admin(auth.uid()));
drop policy if exists "Admins update orders" on public.orders;
create policy "Admins update orders" on public.orders for update to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
drop policy if exists "Admins read order items" on public.order_items;
create policy "Admins read order items" on public.order_items for select to authenticated using (public.is_admin(auth.uid()));
drop policy if exists "Admins read stock movements" on public.stock_movements;
create policy "Admins read stock movements" on public.stock_movements for select to authenticated using (public.is_admin(auth.uid()));

create or replace function public.mark_order_paid(p_order_id uuid,p_payment_provider text,p_payment_reference text)
returns void language plpgsql security definer set search_path = '' as $$
declare item record; current_status text; current_qty integer;
begin
  select payment_status into current_status from public.orders where id=p_order_id for update;
  if current_status is null then raise exception 'Pedido não encontrado'; end if;
  if current_status='paid' then return; end if;
  for item in select oi.beer_id,oi.quantity,oi.beer_name_snapshot from public.order_items oi where oi.order_id=p_order_id loop
    if item.beer_id is not null then
      select stock_quantity into current_qty from public.beers where id=item.beer_id for update;
      if current_qty is not null and current_qty < item.quantity then
        raise exception 'Estoque insuficiente para concluir baixa de %', item.beer_name_snapshot;
      end if;
      update public.beers
      set stock_quantity=case when stock_quantity is null then null else stock_quantity-item.quantity end,
          stock_status=case when stock_quantity is null then stock_status when stock_quantity-item.quantity=0 then 'sold_out' when stock_quantity-item.quantity<=3 then 'low_stock' else 'in_stock' end
      where id=item.beer_id;
      insert into public.stock_movements(beer_id,order_id,movement_type,quantity,note) values(item.beer_id,p_order_id,'sale',-item.quantity,'Baixa automática após pagamento Stripe');
    end if;
  end loop;
  update public.orders set payment_status='paid',status='paid',payment_provider=p_payment_provider,payment_reference=p_payment_reference,paid_at=now(),updated_at=now() where id=p_order_id;
end;
$$;
revoke all on function public.mark_order_paid(uuid,text,text) from public,anon,authenticated;

create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists stock_movements_beer_id_idx on public.stock_movements(beer_id);
