(()=>{'use strict';
const URL='https://cqtdrpwnjnetbcnuqtyv.supabase.co', KEY='sb_publishable_hY5y6tve470_iBtkQuQiLw_Vs38_nBy', FIRST_ADMIN='ameninadovideo016@gmail.com';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; let session=null, beers=[], settingsRow=null;
const authView=$('#authView'),appView=$('#appView'),authMsg=$('#authMsg'),appMsg=$('#appMsg');
function msg(el,text,type=''){el.textContent=text||'';el.className='message'+(type?' '+type:'')}
async function req(path,{method='GET',body,auth=true,headers={}}={}){const h={apikey:KEY,...headers};if(auth&&session?.access_token)h.Authorization=`Bearer ${session.access_token}`;if(body!==undefined&&!headers['Content-Type'])h['Content-Type']='application/json';const r=await fetch(URL+path,{method,headers:h,body:body===undefined?undefined:(h['Content-Type']==='application/json'?JSON.stringify(body):body)});if(!r.ok){let t=await r.text();try{const j=JSON.parse(t);t=j.message||j.error_description||j.error||t}catch{}throw new Error(t||`Erro ${r.status}`)}if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
function saveSession(s){session=s;localStorage.setItem('cd_admin_session',JSON.stringify(s))}function clearSession(){session=null;localStorage.removeItem('cd_admin_session')}
async function refresh(){if(!session?.refresh_token)return false;try{const s=await req('/auth/v1/token?grant_type=refresh_token',{method:'POST',auth:false,body:{refresh_token:session.refresh_token}});saveSession(s);return true}catch{return false}}
async function ensureAdmin(){const uid=session?.user?.id;if(!uid)return false;const email=(session.user.email||'').toLowerCase();if(email===FIRST_ADMIN){try{const rows=await req(`/rest/v1/admin_users?user_id=eq.${encodeURIComponent(uid)}&select=user_id`);if(rows?.length)return true;try{await req('/rest/v1/admin_users',{method:'POST',body:{user_id:uid},headers:{Prefer:'return=minimal'}})}catch(err){console.warn('Não foi possível sincronizar admin_users; acesso autenticado do primeiro administrador será mantido.',err)}return true}catch(err){console.warn('Validação de admin_users indisponível; acesso autenticado do primeiro administrador será mantido.',err);return true}}try{const rows=await req(`/rest/v1/admin_users?user_id=eq.${encodeURIComponent(uid)}&select=user_id`);return !!rows?.length}catch(err){console.warn('Falha ao validar administrador.',err);return false}}
async function validateSession(){if(!session?.access_token)return false;try{const user=await req('/auth/v1/user');if(!user?.id)return false;session.user=user;saveSession(session);return true}catch{return false}}
async function enter(){if(!(await validateSession())){clearSession();throw new Error('Sua sessão expirou. Faça login novamente.')}if(!(await ensureAdmin())){clearSession();throw new Error('Esta conta não possui permissão de administrador.')}authView.hidden=true;appView.hidden=false;document.body.classList.add('admin-authenticated');$('#adminEmail').textContent=session.user.email||'';try{await loadAll()}catch(err){msg(appMsg,err.message||'O painel abriu, mas houve falha ao carregar alguns dados.','error')}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();msg(authMsg,'Entrando…');try{const s=await req('/auth/v1/token?grant_type=password',{method:'POST',auth:false,body:{email:$('#email').value.trim(),password:$('#password').value}});saveSession(s);await enter();msg(authMsg,'')}catch(err){msg(authMsg,err.message,'error')}});
$('#togglePassword').addEventListener('click',()=>{const input=$('#password'),show=input.type==='password';input.type=show?'text':'password';$('#togglePassword').setAttribute('aria-label',show?'Ocultar senha':'Mostrar senha');$('#togglePassword').setAttribute('aria-pressed',String(show));});
$('#resetBtn').addEventListener('click',async()=>{const email=$('#email').value.trim();if(!email)return msg(authMsg,'Informe o e-mail primeiro.','error');try{await req('/auth/v1/recover',{method:'POST',auth:false,body:{email}});msg(authMsg,'Se a conta existir, o Supabase enviará o e-mail de recuperação.','success')}catch(err){msg(authMsg,err.message,'error')}});
$('#logoutBtn').addEventListener('click',async()=>{try{await req('/auth/v1/logout',{method:'POST'})}catch{}clearSession();location.reload()});
function setView(name){$$('.view').forEach(v=>v.hidden=v.id!==name+'View');$$('.nav[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageTitle').textContent={dashboard:'Visão geral',beers:'Cervejas',orders:'Pedidos',settings:'Configurações'}[name];if(innerWidth<901)$('.sidebar').classList.remove('open')}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.go)));$('#menuBtn').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
async function loadAll(){msg(appMsg,'Carregando dados…');try{await Promise.all([loadBeers(),loadOrders(),loadSettings()]);msg(appMsg,'')}catch(err){msg(appMsg,err.message,'error')}}
async function loadBeers(){beers=await req('/rest/v1/beers?select=*&order=sort_order.asc');renderBeers();$('#statTotal').textContent=beers.length;$('#statActive').textContent=beers.filter(b=>b.active).length;$('#statSold').textContent=beers.filter(b=>b.stock_status==='sold_out').length;renderRecent()}
function stockLabel(s){return s==='sold_out'?'Esgotado':s==='low_stock'?'Últimas unidades':'Em estoque'}function price(v){return v==null?'Preço sob consulta':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function beerImage(src){if(!src)return '/assets/favicon.png';const value=String(src).trim();if(/^https?:\/\//i.test(value)||value.startsWith('data:')||value.startsWith('blob:')||value.startsWith('/'))return value;return '/'+value.replace(/^\.\//,'').replace(/^\.\.\//,'')}
function setBeerImage(img,src){img.src=beerImage(src);img.addEventListener('error',()=>{if(!img.dataset.fallback){img.dataset.fallback='1';img.src='/assets/favicon.png'}},{once:true})}
function beerRow(b,mini=false){const row=document.createElement('div');row.className=mini?'mini-row':'beer-row';const img=document.createElement('img');setBeerImage(img,b.image_url);img.alt='';const info=document.createElement('div');info.className='beer-row-info';const h=document.createElement('h4');h.textContent=b.title||b.name;const p=document.createElement('p');p.textContent=`${b.style||'Estilo não informado'} · ${b.volume||'Volume não informado'} · ${price(b.price)}`;info.append(h,p);if(!mini){const specs=document.createElement('div');specs.className='beer-admin-specs';[['Cervejaria',b.brewery],['ABV',b.abv],['IBU',b.ibu],['Lúpulos',b.hops],['Intensidade',b.intensity],['Amargor',b.bitterness]].forEach(([label,value])=>{const item=document.createElement('span');item.innerHTML=`<b>${label}:</b> ${value||'Não informado'}`;specs.append(item)});info.append(specs)}const badge=document.createElement('span');badge.className='badge';badge.textContent=b.active?stockLabel(b.stock_status):'Inativo';row.append(img,info,badge);if(!mini){const btn=document.createElement('button');btn.className='edit-btn';btn.textContent='Editar';btn.addEventListener('click',()=>openEditor(b));row.append(btn)}return row}
function renderBeers(){const q=$('#beerSearch').value.trim().toLowerCase(),list=$('#beerList');list.replaceChildren();beers.filter(b=>!q||`${b.title} ${b.name} ${b.brewery} ${b.brand}`.toLowerCase().includes(q)).forEach(b=>list.append(beerRow(b)))}$('#beerSearch').addEventListener('input',renderBeers);
function renderRecent(){const el=$('#recentBeers');el.replaceChildren();beers.slice(0,5).forEach(b=>el.append(beerRow(b,true)))}
async function loadOrders(){const orders=await req('/rest/v1/orders?select=*&order=created_at.desc&limit=30');$('#statOrders').textContent=orders.length;const el=$('#ordersList');el.replaceChildren();if(!orders.length){const p=document.createElement('p');p.className='muted';p.textContent='Nenhum pedido registrado no banco ainda.';el.append(p);return}orders.forEach(o=>{const r=document.createElement('div');r.className='order-row';const a=document.createElement('strong');a.textContent=o.order_code||o.id.slice(0,8);const b=document.createElement('span');b.textContent=o.customer_name||'Cliente';const c=document.createElement('span');c.className='badge';c.textContent=o.status||'novo';r.append(a,b,c);el.append(r)})}
async function loadSettings(){const rows=await req('/rest/v1/site_settings?select=*&limit=1');settingsRow=rows?.[0]||null;$('#setWhatsapp').value=settingsRow?.whatsapp||'';$('#setInstagram').value=settingsRow?.instagram||''}
$('#settingsForm').addEventListener('submit',async e=>{e.preventDefault();try{const body={whatsapp:$('#setWhatsapp').value.trim(),instagram:$('#setInstagram').value.trim()};if(settingsRow)await req(`/rest/v1/site_settings?id=eq.${settingsRow.id}`,{method:'PATCH',body,headers:{Prefer:'return=minimal'}});else await req('/rest/v1/site_settings',{method:'POST',body,headers:{Prefer:'return=minimal'}});await loadSettings();msg(appMsg,'Configurações salvas.','success')}catch(err){msg(appMsg,err.message,'error')}});
const dlg=$('#beerDialog');function val(id,v=''){const e=$(id);if(e)e.value=v??''}function openEditor(b=null){$('#beerForm').reset();$$('input[name=tag]').forEach(x=>x.checked=false);$('#imagePreview').removeAttribute('src');$('#deactivateBtn').hidden=!b;$('#editorTitle').textContent=b?'Editar cerveja':'Nova cerveja';val('#beerId',b?.id);val('#fBrand',b?.brand);val('#fName',b?.name);val('#fTitle',b?.title);val('#fSlug',b?.slug);val('#fStyle',b?.style);val('#fBrewery',b?.brewery);val('#fVolume',b?.volume);val('#fPrice',b?.price);val('#fAbv',b?.abv);val('#fIbu',b?.ibu);val('#fHops',b?.hops);val('#fSort',b?.sort_order??beers.length+1);val('#fIntensity',b?.intensity||'🟢 Leve');val('#fBitterness',b?.bitterness||'🟢 Muito baixo');val('#fStock',b?.stock_status||'in_stock');$('#fActive').checked=b?.active!==false;val('#fProfile',b?.profile);val('#fRecommendation',b?.recommendation);val('#fDescription',b?.description);if(b?.image_url)setBeerImage($('#imagePreview'),b.image_url);msg($('#editorMsg'),'');dlg.showModal();if(b)loadTags(b.id)}
async function loadTags(id){try{const tags=await req(`/rest/v1/beer_tags?beer_id=eq.${encodeURIComponent(id)}&select=tag`);const set=new Set(tags.map(t=>t.tag));$$('input[name=tag]').forEach(x=>x.checked=set.has(x.value))}catch(err){msg($('#editorMsg'),err.message,'error')}}
$('#newBeerBtn').addEventListener('click',()=>openEditor());$('#newBeerTop').addEventListener('click',()=>openEditor());$('#closeDialog').addEventListener('click',()=>dlg.close());dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});
$('#fImage').addEventListener('change',()=>{const f=$('#fImage').files[0];if(f)$('#imagePreview').src=URL.createObjectURL(f)});
async function uploadImage(file,slug){if(!file)return null;if(file.size>5*1024*1024)throw new Error('A imagem ultrapassa 5 MB.');const ext=(file.name.split('.').pop()||'webp').toLowerCase();const path=`${slug}-${Date.now()}.${ext}`;await req(`/storage/v1/object/beer-images/${encodeURIComponent(path)}`,{method:'POST',body:file,headers:{'Content-Type':file.type||'application/octet-stream','x-upsert':'false'}});return `${URL}/storage/v1/object/public/beer-images/${path}`}
$('#beerForm').addEventListener('submit',async e=>{e.preventDefault();const out=$('#editorMsg');msg(out,'Salvando…');try{const existingId=$('#beerId').value||null,slug=$('#fSlug').value.trim();let image=existingId?beers.find(b=>b.id===existingId)?.image_url:null;const file=$('#fImage').files[0];if(file)image=await uploadImage(file,slug);const body={slug,brand:$('#fBrand').value.trim(),name:$('#fName').value.trim(),title:$('#fTitle').value.trim(),subtitle:$('#fStyle').value.trim(),style:$('#fStyle').value.trim(),brewery:$('#fBrewery').value.trim(),volume:$('#fVolume').value.trim(),price:$('#fPrice').value===''?null:Number($('#fPrice').value),abv:$('#fAbv').value.trim(),ibu:$('#fIbu').value.trim(),hops:$('#fHops').value.trim(),description:$('#fDescription').value.trim(),intensity:$('#fIntensity').value,bitterness:$('#fBitterness').value,profile:$('#fProfile').value.trim(),recommendation:$('#fRecommendation').value.trim(),image_url:image,image_alt:$('#fTitle').value.trim(),active:$('#fActive').checked,stock_status:$('#fStock').value,sort_order:Number($('#fSort').value)||0,order_name:$('#fTitle').value.trim()};let beerId=existingId;if(existingId)await req(`/rest/v1/beers?id=eq.${encodeURIComponent(existingId)}`,{method:'PATCH',body,headers:{Prefer:'return=minimal'}});else{const created=await req('/rest/v1/beers',{method:'POST',body,headers:{Prefer:'return=representation'}});beerId=created[0].id}await req(`/rest/v1/beer_tags?beer_id=eq.${encodeURIComponent(beerId)}`,{method:'DELETE'});const tags=$$('input[name=tag]:checked').map(x=>({beer_id:beerId,tag:x.value}));if(tags.length)await req('/rest/v1/beer_tags',{method:'POST',body:tags,headers:{Prefer:'return=minimal'}});await loadBeers();msg(out,'Cerveja salva e catálogo atualizado.','success');setTimeout(()=>dlg.close(),650)}catch(err){msg(out,err.message,'error')}});
$('#deactivateBtn').addEventListener('click',async()=>{const id=$('#beerId').value;if(!id)return;try{await req(`/rest/v1/beers?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{active:false},headers:{Prefer:'return=minimal'}});await loadBeers();dlg.close();msg(appMsg,'Cerveja desativada.','success')}catch(err){msg($('#editorMsg'),err.message,'error')}});
(async()=>{try{const raw=localStorage.getItem('cd_admin_session');if(!raw)return;session=JSON.parse(raw);if(!session?.access_token)return clearSession();if(session.expires_at&&Date.now()/1000>session.expires_at-30)await refresh();await enter()}catch{clearSession()}})();
})();
