(()=>{'use strict';
const $=s=>document.querySelector(s),money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const BASE='https://cqtdrpwnjnetbcnuqtyv.supabase.co',KEY='sb_publishable_hY5y6tve470_iBtkQuQiLw_Vs38_nBy';
let partners=[],moves=[],settlements=[],beers=[],visits=[],activePartner=null;
function token(){try{return JSON.parse(localStorage.getItem('cd_admin_session')||'{}').access_token}catch{return null}}
async function api(table,{method='GET',body,query='',prefer='return=representation'}={}){const jwt=token();if(!jwt)throw Error('Faça login novamente.');const r=await fetch(`${BASE}/rest/v1/${table}${query}`,{method,headers:{apikey:KEY,Authorization:`Bearer ${jwt}`,'Content-Type':'application/json',Prefer:prefer},body:body?JSON.stringify(body):undefined});if(!r.ok){const t=await r.text();throw Error(t.includes('relation')||t.includes('does not exist')?'Execute o arquivo supabase-parceiros-consignacao.sql no Supabase antes de utilizar este módulo.':t)}if(r.status===204)return [];return r.json()}
function say(selector,message,type=''){const e=$(selector);if(e){e.textContent=message;e.className='message '+type}}
function qty(m){return m.movement_type==='delivery'?m.quantity:m.movement_type==='adjustment'?m.quantity:-m.quantity}
function stats(id){const selected=moves.filter(m=>!id||m.partner_id===id), sales=selected.filter(m=>m.movement_type==='sale');const received=settlements.filter(s=>!id||s.partner_id===id).reduce((a,s)=>a+Number(s.amount),0);const due=sales.reduce((a,m)=>a+Number(m.quantity)*Number(m.unit_price)*(1-Number(m.partner_share)/100),0);const stocks=new Map();selected.forEach(m=>{const key=m.partner_id+':'+m.beer_id;const x=stocks.get(key)||{partner_id:m.partner_id,beer_id:m.beer_id,quantity:0,unit_cost:0,unit_price:0};x.quantity+=qty(m);if(m.movement_type==='delivery'||m.movement_type==='adjustment'&&m.quantity>0){x.unit_cost=Number(m.unit_cost);x.unit_price=Number(m.unit_price)}stocks.set(key,x)});const items=[...stocks.values()].filter(x=>x.quantity>0);return {items,capital:items.reduce((a,x)=>a+x.quantity*x.unit_cost,0),retail:items.reduce((a,x)=>a+x.quantity*x.unit_price,0),received,pending:due-received,sold:sales.reduce((a,m)=>a+m.quantity,0)}}
function partnerName(id){return partners.find(p=>p.id===id)?.name||'Parceiro removido'}
function beerName(id){const b=beers.find(x=>x.id===id);return b?.title||b?.name||'Cerveja'}
function render(){const id=$('#conPartnerFilter').value,overall=stats(id);$('#conCapital').textContent=money(overall.capital);$('#conRetail').textContent=money(overall.retail);$('#conPending').textContent=money(overall.pending);$('#conReceived').textContent=money(overall.received);
const filter=$('#conPartnerFilter');filter.replaceChildren(new Option('Todos os parceiros',''));partners.forEach(p=>filter.add(new Option(p.name,p.id)));filter.value=id;
const list=$('#conPartnerList');list.replaceChildren();partners.filter(p=>!id||p.id===id).forEach(p=>{const x=stats(p.id),card=document.createElement('article');card.className='consignment-partner';card.innerHTML=`<div><h4>${esc(p.name)}</h4><p>${esc(p.sales_contact)} · ${esc(p.cnpj||'CNPJ não informado')} · Geladeira ${esc(p.fridge_code||'sem código')}</p><p>${esc(p.phone||'')} · ${esc(p.address||'')}</p><p>${x.items.reduce((a,i)=>a+i.quantity,0)} latas · Capital ${money(x.capital)} · Venda potencial ${money(x.retail)} · A receber ${money(x.pending)} · Recebido ${money(x.received)}</p><small>Comissão parceiro: ${p.partner_share}% · ${p.status==='active'?'Ativo':p.status==='watch'?'Em observação':'Inativo'}</small></div><div class="consignment-actions"><button type="button" data-action="detail">Abrir painel</button><button type="button" data-action="edit">Editar</button><button type="button" data-action="move">Movimentar latas</button><button type="button" data-action="settle">Registrar repasse</button></div>`;card.querySelector('[data-action="detail"]').onclick=()=>openDetail(p);card.querySelector('[data-action="edit"]').onclick=()=>openPartner(p);card.querySelector('[data-action="move"]').onclick=()=>openMovement(p);card.querySelector('[data-action="settle"]').onclick=()=>openSettlement(p);list.append(card)});
const body=$('#conStockRows');body.replaceChildren();overall.items.forEach(x=>{const tr=document.createElement('tr');[partnerName(x.partner_id),beerName(x.beer_id),x.quantity,money(x.quantity*x.unit_cost),money(x.quantity*x.unit_price)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});body.append(tr)});if(!overall.items.length){const tr=document.createElement('tr');tr.innerHTML='<td colspan="5">Nenhuma lata consignada registrada.</td>';body.append(tr)}
const history=$('#conHistory');history.replaceChildren();moves.filter(m=>!id||m.partner_id===id).slice(0,20).forEach(m=>{const row=document.createElement('div');row.className='consignment-history';const names={delivery:'Abastecimento',sale:'Venda',return:'Devolução',loss:'Perda',adjustment:'Ajuste'};row.textContent=`${new Date(m.created_at).toLocaleString('pt-BR')} · ${partnerName(m.partner_id)} · ${beerName(m.beer_id)} · ${names[m.movement_type]} ${m.quantity} un. · ${money(m.unit_price)}/un.`;history.append(row)});if(!moves.length)history.textContent='Sem movimentações registradas.'}
window.loadConsignment=async()=>{if(!token())return;try{[partners,moves,settlements,visits]=await Promise.all([api('consignment_partners',{query:'?select=*&order=name.asc'}),api('consignment_movements',{query:'?select=*&order=created_at.desc&limit=10000'}),api('consignment_settlements',{query:'?select=*&order=paid_at.desc&limit=10000'}),api('consignment_visits',{query:'?select=*&order=visited_on.desc&limit=10000'})]);beers=window.consignmentBeers||[];if(!beers.length)beers=await api('beers',{query:'?select=id,title,name,price'});render();if(activePartner){const p=partners.find(x=>x.id===activePartner.id);if(p)openDetail(p)}say('#consignmentMsg','')}catch(e){say('#consignmentMsg',e.message,'error')}};
function openPartner(p){$('#conPartnerForm').reset();$('#conPartnerId').value=p?.id||'';$('#conPartnerTitle').textContent=p?'Editar parceiro':'Novo parceiro';[['#conName','name'],['#conCnpj','cnpj'],['#conContact','sales_contact'],['#conPhone','phone'],['#conAddress','address'],['#conFridge','fridge_code'],['#conShare','partner_share'],['#conStatus','status']].forEach(([selector,key])=>{if(p?.[key]!=null)$(selector).value=p[key]});$('#conPartnerDialog').showModal()}
$('#newPartnerBtn').onclick=()=>openPartner();$('#conPartnerCancel').onclick=()=>$('#conPartnerDialog').close();
$('#conPartnerForm').onsubmit=async e=>{e.preventDefault();try{const id=$('#conPartnerId').value,cnpj=$('#conCnpj').value.replace(/\D/g,'');if(cnpj&&cnpj.length!==14)throw Error('CNPJ deve conter 14 dígitos.');const body={name:$('#conName').value.trim(),cnpj:cnpj||null,sales_contact:$('#conContact').value.trim(),phone:$('#conPhone').value.trim(),address:$('#conAddress').value.trim(),fridge_code:$('#conFridge').value.trim(),partner_share:Number($('#conShare').value),status:$('#conStatus').value};await api('consignment_partners',{method:id?'PATCH':'POST',query:id?`?id=eq.${encodeURIComponent(id)}`:'',body});$('#conPartnerDialog').close();await window.loadConsignment()}catch(e){say('#conPartnerMsg',e.message,'error')}};
function openMovement(p){$('#conMovementForm').reset();$('#conMovementPartner').value=p.id;$('#conMovementTitle').textContent='Movimentação · '+p.name;const sel=$('#conBeer');sel.replaceChildren();beers.forEach(b=>sel.add(new Option((b.title||b.name)+' · '+money(b.price),b.id)));updateBeer();$('#conMovementDialog').showModal()}
function updateBeer(){const b=beers.find(x=>x.id===$('#conBeer').value);$('#conPrice').value=b?.price??0;const p=partners.find(x=>x.id===$('#conMovementPartner').value),previous=moves.find(m=>m.partner_id===p?.id&&m.beer_id===b?.id&&m.movement_type==='delivery');$('#conCost').value=previous?.unit_cost??0}
$('#conBeer').onchange=updateBeer;$('#conMovementCancel').onclick=()=>$('#conMovementDialog').close();
$('#conMovementForm').onsubmit=async e=>{e.preventDefault();try{const type=$('#conMovementType').value,n=Number($('#conQuantity').value),partner_id=$('#conMovementPartner').value,beer_id=$('#conBeer').value;if(!Number.isInteger(n)||n<1)throw Error('Informe quantidade inteira positiva.');const quantity=type==='adjustment'&&$('#conNotes').value.trim().startsWith('-')?-n:n;const body={partner_id,beer_id,movement_type:type,quantity,unit_cost:Number($('#conCost').value),unit_price:Number($('#conPrice').value),partner_share:Number(partners.find(p=>p.id===partner_id)?.partner_share||50),notes:$('#conNotes').value.trim()};await api('consignment_movements',{method:'POST',body});$('#conMovementDialog').close();await window.loadConsignment()}catch(e){say('#conMovementMsg',e.message,'error')}};
function openSettlement(p){$('#conSettlementForm').reset();$('#conSettlementPartner').value=p.id;const due=stats(p.id).pending;$('#conSettlementPending').textContent=`Valor pendente calculado: ${money(due)}`;$('#conSettlementAmount').max=String(Math.max(0,due));$('#conSettlementDialog').showModal()}
$('#conSettlementCancel').onclick=()=>$('#conSettlementDialog').close();$('#conSettlementForm').onsubmit=async e=>{e.preventDefault();try{const partner_id=$('#conSettlementPartner').value,amount=Number($('#conSettlementAmount').value);if(amount<=0||amount>stats(partner_id).pending+0.001)throw Error('Valor inválido ou superior ao repasse pendente.');await api('consignment_settlements',{method:'POST',body:{partner_id,amount,notes:$('#conSettlementNotes').value.trim()}});$('#conSettlementDialog').close();await window.loadConsignment()}catch(e){say('#conSettlementMsg',e.message,'error')}};
$('#conPartnerFilter').onchange=render;$('#conRefresh').onclick=()=>window.loadConsignment();$('#conExport').onclick=()=>{const rows=[['Parceiro','Cerveja','Quantidade','Custo em estoque','Venda potencial'],...stats($('#conPartnerFilter').value).items.map(x=>[partnerName(x.partner_id),beerName(x.beer_id),x.quantity,(x.quantity*x.unit_cost).toFixed(2),(x.quantity*x.unit_price).toFixed(2)])];const csv='\ufeff'+rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='consignacao-estoque.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};

function detailRows(id){return stats(id).items.filter(i=>i.partner_id===id)}
function openDetail(p){activePartner=p;$('#conPartnerDetail').hidden=false;$('#conPartnerList').closest('.consignment-panel').hidden=true;$('#conDetailName').textContent=p.name;$('#conDetailMeta').textContent=`${p.sales_contact} · ${p.cnpj||'Sem CNPJ'} · Geladeira ${p.fridge_code||'não identificada'} · Participação do parceiro ${p.partner_share}%`;const x=stats(p.id),ms=moves.filter(m=>m.partner_id===p.id),delivered=ms.filter(m=>m.movement_type==='delivery').reduce((a,m)=>a+Number(m.quantity),0),sold=ms.filter(m=>m.movement_type==='sale').reduce((a,m)=>a+Number(m.quantity),0),current=x.items.reduce((a,i)=>a+i.quantity,0),due=Math.max(0,x.pending),cards=[['Latas abastecidas',delivered],['Latas vendidas',sold],['Latas em estoque',current],['Capital parado',money(x.capital)],['Venda potencial',money(x.retail)],['Repasse pendente',money(due)],['Recebido',money(x.received)],['Visitas registradas',visits.filter(v=>v.partner_id===p.id).length]];$('#conDetailKpis').innerHTML=cards.map(([label,value])=>`<article><span>${esc(label)}</span><strong>${esc(value)}</strong></article>`).join('');$('#conDetailFinance').innerHTML=`<p>Total vendido ao consumidor: <b>${money(ms.filter(m=>m.movement_type==='sale').reduce((a,m)=>a+m.quantity*m.unit_price,0))}</b></p><p>Repasse acumulado ao Diegão: <b>${money(x.received+x.pending)}</b></p><p>Última visita: <b>${esc(visits.filter(v=>v.partner_id===p.id)[0]?.visited_on||'Ainda não registrada')}</b></p>`;$('#conContractInfo').textContent=p.contract_name?`Contrato: ${p.contract_name}`:'Nenhum contrato anexado';$('#conOpenContract').disabled=!p.contract_path;const tbody=$('#conDetailStock');tbody.replaceChildren();x.items.forEach(i=>{const soldBeer=ms.filter(m=>m.beer_id===i.beer_id&&m.movement_type==='sale').reduce((a,m)=>a+m.quantity,0),tr=document.createElement('tr');[beerName(i.beer_id),i.quantity,soldBeer,money(i.quantity*i.unit_cost),money(i.quantity*i.unit_price)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});tbody.append(tr)});if(!x.items.length)tbody.innerHTML='<tr><td colspan="5">Sem estoque nesta geladeira.</td></tr>';const list=$('#conVisitsList');list.replaceChildren();visits.filter(v=>v.partner_id===p.id).forEach(v=>{const row=document.createElement('article');row.className='consignment-history';row.textContent=`${new Date(v.visited_on+'T12:00:00').toLocaleDateString('pt-BR')} · ${v.units_sold} latas vendidas · Vendas ${money(v.gross_sales)} · Repasse gerado ${money(v.due_amount)} · Recebido ${money(v.received_amount)}${v.notes?' · '+v.notes:''}`;list.append(row)});if(!list.children.length)list.textContent='Nenhuma visita registrada. Faça a primeira conferência.';}
$('#conBack').onclick=()=>{activePartner=null;$('#conPartnerDetail').hidden=true;$('#conPartnerList').closest('.consignment-panel').hidden=false};
$('#conDetailMovement').onclick=()=>activePartner&&openMovement(activePartner);
$('#conDetailSettlement').onclick=()=>activePartner&&openSettlement(activePartner);
async function storage(path,opts={}){const jwt=token();const response=await fetch(`${BASE}/storage/v1/${path}`,{...opts,headers:{apikey:KEY,Authorization:`Bearer ${jwt}`,...opts.headers}});if(!response.ok)throw Error(await response.text());return response.json()}
$('#conUploadContract').onclick=async()=>{try{if(!activePartner)throw Error('Selecione o parceiro.');const f=$('#conContractFile').files[0];if(!f)throw Error('Selecione um contrato.');if(f.size>10*1024*1024)throw Error('Arquivo acima do limite de 10 MB.');if(!/\.(pdf|png|jpe?g|docx?)$/i.test(f.name))throw Error('Formato não permitido.');const path=`${activePartner.id}/${crypto.randomUUID()}.${f.name.split('.').pop().toLowerCase()}`;await storage(`object/consignment-contracts/${path}`,{method:'POST',headers:{'Content-Type':f.type||'application/octet-stream','x-upsert':'false'},body:f});await api('consignment_partners',{method:'PATCH',query:`?id=eq.${activePartner.id}`,body:{contract_path:path,contract_name:f.name}});say('#conContractMsg','Contrato anexado com sucesso.');await window.loadConsignment()}catch(e){say('#conContractMsg',e.message,'error')}};
$('#conOpenContract').onclick=async()=>{try{if(!activePartner?.contract_path)return;const d=await storage('object/sign/consignment-contracts/'+activePartner.contract_path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expiresIn:120})});window.open(`${BASE}/storage/v1${d.signedURL}`,'_blank','noopener,noreferrer')}catch(e){say('#conContractMsg',e.message,'error')}};
$('#conNewVisit').onclick=()=>{if(!activePartner)return;$('#conVisitForm').reset();$('#conVisitPartnerName').textContent=activePartner.name;$('#conVisitDate').value=new Date().toLocaleDateString('en-CA');const rows=$('#conVisitBeerRows');rows.replaceChildren();detailRows(activePartner.id).forEach(i=>{const label=document.createElement('label');label.className='consignment-visit-row';label.innerHTML=`<span>${esc(beerName(i.beer_id))}<small>Saldo esperado: ${i.quantity} latas · ${money(i.unit_price)} / lata</small></span><input type="number" min="0" max="${i.quantity}" step="1" value="${i.quantity}" required data-beer="${esc(i.beer_id)}" data-expected="${i.quantity}" data-price="${i.unit_price}" data-cost="${i.unit_cost}">`;rows.append(label)});if(!rows.children.length){say('#conDetailMsg','Primeiro registre o abastecimento da geladeira.','error');return}$('#conVisitPreview').textContent='';$('#conVisitDialog').showModal()};
$('#conVisitCancel').onclick=()=>$('#conVisitDialog').close();
function visitEntries(){return [...document.querySelectorAll('#conVisitBeerRows input')].map(el=>({beer_id:el.dataset.beer,expected:Number(el.dataset.expected),remaining:Number(el.value),price:Number(el.dataset.price),cost:Number(el.dataset.cost)}))}
function previewVisit(){const entries=visitEntries(),sold=entries.reduce((a,e)=>a+e.expected-e.remaining,0),gross=entries.reduce((a,e)=>a+(e.expected-e.remaining)*e.price,0),due=gross*(1-Number(activePartner?.partner_share||50)/100);$('#conVisitPreview').textContent=`Vendidas: ${sold} latas · Valor de venda: ${money(gross)} · Repasse desta visita: ${money(due)}`}
$('#conVisitBeerRows').addEventListener('input',previewVisit);
$('#conVisitForm').onsubmit=async e=>{e.preventDefault();try{const entries=visitEntries();if(entries.some(i=>!Number.isInteger(i.remaining)||i.remaining<0||i.remaining>i.expected))throw Error('A contagem deve ser inteira e não pode superar o saldo esperado. Registre reposições separadamente.');const received=Number($('#conVisitReceived').value),gross=entries.reduce((a,i)=>a+(i.expected-i.remaining)*i.price,0),due=gross*(1-Number(activePartner.partner_share)/100),available=Math.max(0,stats(activePartner.id).pending);if(!Number.isFinite(received)||received<0||received>available+due+.001)throw Error('Valor recebido maior que o repasse pendente mais as vendas desta visita.');$('#conVisitSave').disabled=true;await rpc('consignment_register_visit',{p_partner_id:activePartner.id,p_visited_on:$('#conVisitDate').value,p_notes:$('#conVisitNotes').value.trim(),p_received:received,p_items:entries});$('#conVisitDialog').close();await window.loadConsignment()}catch(err){say('#conVisitMsg',err.message,'error')}finally{$('#conVisitSave').disabled=false}};
async function rpc(name,body){const jwt=token(),response=await fetch(`${BASE}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${jwt}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw Error(await response.text());return response.json()}

})();
